default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  

development:
  <<: *default
  database: see_development
  username: m
  password: postgres

test:
  <<: *default
  database: see_test
  username: m
  password: postgres

production:
  <<: *default
  database: see_production
